In [42]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
import numpy as np
x = np.arange(9)
print(x)
x<10
y = x<10
z = y.reshape(3, 3)
print(z)

[0 1 2 3 4 5 6 7 8]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [46]:
a = np.arange(1, 11)
print(a)
[x for x in a if x % 2 == 1]
    

[ 1  2  3  4  5  6  7  8  9 10]


[1, 3, 5, 7, 9]

In [47]:
a = np.arange(1,11)
odd_values = (a%2 == 1)
a[odd_values] = -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [49]:
one_d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
two_d_array = one_d_array.reshape(2, 5)
print(two_d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [50]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)
print(a)
print(b)
c = np.dot(a, b)
print(c)
d = np.sum(c)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]
13648
