In [2]:
empty_list = [1, "Hello", 2.4, "Now"]
my_1d_list = ["Suzannah", "Andy", "Georgina", "Satinder", "Ruth", "Irina", "Natasha", "Alison", ]
print (my_1d_list) 
print(empty_list)

['Suzannah', 'Andy', 'Georgina', 'Satinder', 'Ruth', 'Irina', 'Natasha', 'Alison']
[1, 'Hello', 2.4, 'Now']


In [3]:
my_1d_list[4]

'Ruth'

In [4]:
for i in range(len(my_1d_list)):
    print("The data at index location", i, "is:", my_1d_list[i])

The data at index location 0 is: Suzannah
The data at index location 1 is: Andy
The data at index location 2 is: Georgina
The data at index location 3 is: Satinder
The data at index location 4 is: Ruth
The data at index location 5 is: Irina
The data at index location 6 is: Natasha
The data at index location 7 is: Alison


In [5]:
print(len(my_1d_list))

8


In [6]:
my_1d_list[1:5]

['Andy', 'Georgina', 'Satinder', 'Ruth']

In [7]:
my_2d_list = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
my_2d_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [10]:
my_file = open("my_new_text_file.txt", "w")

for i in range(10):
    my_file.write(str(i))
    my_file.write("\n")




In [15]:
my_file = open("my_new_text_file.txt", "r")
print(my_file)

<_io.TextIOWrapper name='my_new_text_file.txt' mode='r' encoding='cp1252'>


In [16]:
import pandas as pd

In [17]:
# setup a one dimensional array-like object
# The word Series must start with a capital letter otherwise you get a syntax error


myseries = pd.Series([439, 98.54, 'Hello World', 'Sea Breeze', -342])
mylist = [439, 98.54, 'Hello World', 'Sea Breeze', -342]

# print the data in series
print(myseries)
print(mylist)

# when the data is printed what do you notice?

0            439
1          98.54
2    Hello World
3     Sea Breeze
4           -342
dtype: object
[439, 98.54, 'Hello World', 'Sea Breeze', -342]


In [18]:
inventory = {"Name": ["Alex", "Mimi", "Maka", "Nyasha"],
             "Age": [46, 44, 10, 4],
             "Genda":["Male", "Female", "Female", "Female"],
             "Height": [180, 156, 145, 98]}

print(inventory)

myframe = pd.DataFrame(inventory)

print(myframe)


{'Name': ['Alex', 'Mimi', 'Maka', 'Nyasha'], 'Age': [46, 44, 10, 4], 'Genda': ['Male', 'Female', 'Female', 'Female'], 'Height': [180, 156, 145, 98]}
     Name  Age   Genda  Height
0    Alex   46    Male     180
1    Mimi   44  Female     156
2    Maka   10  Female     145
3  Nyasha    4  Female      98


In [19]:
myframe.index = ["AL", "MI", "MA", "NY"]
print(myframe)

      Name  Age   Genda  Height
AL    Alex   46    Male     180
MI    Mimi   44  Female     156
MA    Maka   10  Female     145
NY  Nyasha    4  Female      98


In [34]:
fh = open("demo.txt", "a")

for i in range(10):
    fh.write("this is line no %d\n" % (i+1))

fh.close()

 



In [35]:
with open("demo.txt", "a") as fh:
    for i in range(10):
        fh.write("this is line no %d\n" %(i +1))

In [39]:
my_file = open("data_peeps.txt", "w")

for i in range(10):
    my_file.write(str(i))
    my_file.write("\n")

my_file.close()


In [94]:
with open("Numbers.txt", "w") as mf:
    mf.write("3, 45, 83, 21")
    mf.write("\n")  
  

In [95]:
with open("Numbers.txt", "a") as mf:
    mf.write("3, 45, 83, 21")
    

In [96]:
with open("Numbers.txt", "r") as mf:
   x = mf.read()
   print(x)
print(list)   


3, 45, 83, 21
3, 45, 83, 21


In [86]:
score = int(input())
if(score >= 70 and score <= 100):
    print("You have excelled: ", score, "Grade:A")
elif(score >=60 and  score < 70):
    print("Welldone: ", score, "Grade:B")
elif(score >=50 and score < 60):
    print("You have passed: ", score, "Grade:C")
else:
    print("You have failed")     

You have passed:  54 Grade:C


In [93]:
target_grade = input()
exam_grade = input()
if (target_grade > exam_grade):
    print("Try again")
elif(target_grade == exam_grade):
    print("Welldone")
else:
    print("You have excelled") 


You have excelled


In [102]:
mf = pd.Series([3,5,7,9])

print(mf)


0    3
1    5
2    7
3    9
dtype: int64


In [110]:
import numpy as np

ar = np.array([2, 3, 4, 5,8])
print(ar)

[2 3 4 5 8]


In [111]:
pr = np.arange(0,10)
print(pr)

[0 1 2 3 4 5 6 7 8 9]


In [112]:
ar_to_nine = np.arange(10)
print(ar_to_nine)

[0 1 2 3 4 5 6 7 8 9]
